const MOTION_PLAY_ICON=`<svg viewBox="0 0 1024 1024" aria-hidden="true"><use href="/static/assets/icons.svg?v=2#motion-play"></use></svg>`;
const MOTION_PAUSE_ICON=`<svg viewBox="0 0 1024 1024" aria-hidden="true"><use href="/static/assets/icons.svg?v=2#motion-pause"></use></svg>`;
const MOTION_MUTED_ICON=`<svg viewBox="0 0 1024 1024" aria-hidden="true"><use href="/static/assets/icons.svg?v=1#motion-muted"></use></svg>`;
const MOTION_SOUND_ICON=`<svg viewBox="0 0 1024 1024" aria-hidden="true"><use href="/static/assets/icons.svg?v=1#motion-sound"></use></svg>`;

function viewerSuggestion(p){if(p._viewerBadge)return {text:p._viewerBadge,kind:p._viewerKind};if(p.suggestion==="remove")return {text:"建议移除",kind:"remove"};if(p.suggestion==="review")return {text:"人工复查",kind:"review"};return {text:"",kind:""}}
function syncCardAnalysis(p){const suggestion=viewerSuggestion({...p,_viewerBadge:"",_viewerKind:""});$$(`[data-photo-id="${p.id}"]`).forEach(card=>{const thumb=card.querySelector(".thumb"),contextBadge=thumb?.querySelector("[data-context-badge]");let badge=thumb?.querySelector("[data-analysis-badge]");if(suggestion.text&&!contextBadge){if(!badge){badge=document.createElement("span");badge.dataset.analysisBadge="";thumb.appendChild(badge)}badge.className=`badge badge-${suggestion.kind}`;badge.textContent=suggestion.text}else badge?.remove();const image=card.querySelector("img"),detail=card.querySelector("small");if(image)image.src=p.thumb_url;if(detail)detail.textContent=cardDetailText(p)})}
function updateViewerDecision(p){$("#viewerKeep").classList.toggle("active",p.decision==="keep");$("#viewerRemove").classList.toggle("active",p.decision==="remove")}
function viewerTransformTarget(){return state.viewerMotion.active?$("#viewerVideo"):$("#viewerImage")}
function applyViewerTransform(){const t=state.viewerTransform,target=viewerTransformTarget();[$("#viewerImage"),$("#viewerVideo")].forEach(media=>{if(media!==target){media.style.transform="";media.classList.remove("zoomed","dragging")}});target.style.transform=`translate3d(${t.x}px,${t.y}px,0) scale(${t.scale})`;target.classList.toggle("zoomed",t.scale>1);target.classList.toggle("dragging",t.dragging)}
function clampViewerPan(){const t=state.viewerTransform,target=viewerTransformTarget(),maxX=Math.max(0,target.offsetWidth*(t.scale-1)/2),maxY=Math.max(0,target.offsetHeight*(t.scale-1)/2);t.x=Math.max(-maxX,Math.min(maxX,t.x));t.y=Math.max(-maxY,Math.min(maxY,t.y))}
function resetViewerTransform(){Object.assign(state.viewerTransform,{scale:1,x:0,y:0,dragging:false,moved:false,suppressClick:false});clearTimeout(state.viewerClickTimer);applyViewerTransform()}
function zoomViewer(factor,clientX,clientY){const t=state.viewerTransform,figure=viewerTransformTarget().parentElement,rect=figure.getBoundingClientRect(),old=t.scale,next=Math.max(1,Math.min(8,old*factor));if(next===old)return;const pointX=(clientX??rect.left+rect.width/2)-(rect.left+rect.width/2),pointY=(clientY??rect.top+rect.height/2)-(rect.top+rect.height/2),ratio=next/old;t.x=pointX-(pointX-t.x)*ratio;t.y=pointY-(pointY-t.y)*ratio;t.scale=next;if(next===1){t.x=0;t.y=0}clampViewerPan();applyViewerTransform()}
function motionClock(ms){const seconds=Math.max(0,Math.floor(ms/1000));return `${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,"0")}`}
function lastMotionFrameTime(p){const duration=p?.motion?.duration_ms||0,fps=p?.motion?.fps||0,frameDuration=fps>0?Math.max(1,Math.ceil(1000/fps)):1;return Math.max(0,duration-frameDuration)}
function motionMarkerPosition(time,lastFrame){const percent=lastFrame?time/lastFrame*100:0,edgeOffset=6-percent*0.12;return {percent,position:`calc(${percent}% + ${edgeOffset}px)`}}
function syncMotionCoverMarkers(p){const wrap=$("#motionTimelineWrap"),lastFrame=lastMotionFrameTime(p),motionCover=p?.motion?.cover_source==="motion",stillTime=Math.min(lastFrame,Math.max(0,p?.motion?.still_time_ms||0)),coverTime=motionCover?Math.min(lastFrame,Math.max(0,p.motion.cover_time_ms||0)):stillTime,current=motionMarkerPosition(coverTime,lastFrame),original=motionMarkerPosition(stillTime,lastFrame);wrap.style.setProperty("--motion-cover-percent",`${current.percent}%`);wrap.style.setProperty("--motion-cover-position",current.position);wrap.style.setProperty("--motion-original-position",original.position);$("#motionCoverMarker").title=`当前封面 · ${motionClock(coverTime)}`;$("#motionOriginalMarker").title=`原始封面 · ${motionClock(stillTime)}`;$("#motionOriginalMarker").classList.toggle("hidden",!motionCover||Math.abs(coverTime-stillTime)<1)}
function stopViewerMotion(){const video=$("#viewerVideo");video.pause();video.removeAttribute("src");video.load();video.classList.add("hidden");$("#motionControls").classList.add("hidden");$("#viewer").classList.remove("viewer-motion-open");state.viewerMotion={active:false,scrubbing:false}}
function syncMotionTime(){const p=state.items[state.viewerIndex],duration=p?.motion?.duration_ms||0,current=Math.round(($("#viewerVideo").currentTime||0)*1000),timeline=$("#motionTimeline"),play=$("#motionPlay"),paused=$("#viewerVideo").paused;timeline.value=String(Math.min(lastMotionFrameTime(p),current));timeline.style.setProperty("--motion-progress",`${duration?Math.min(100,current/duration*100):0}%`);$("#motionTime").textContent=`${motionClock(current)} / ${motionClock(duration)}`;play.innerHTML=paused?MOTION_PLAY_ICON:MOTION_PAUSE_ICON;play.setAttribute("aria-label",paused?"播放":"暂停");play.title=paused?"播放":"暂停"}
function syncMotionVolume(){const video=$("#viewerVideo"),button=$("#motionMute"),muted=video.muted;button.innerHTML=muted?MOTION_MUTED_ICON:MOTION_SOUND_ICON;button.setAttribute("aria-label",muted?"播放声音":"静音");button.title=muted?"播放声音":"静音"}
function toggleMotionPlayback(){const video=$("#viewerVideo");if(video.paused){if(video.ended)video.currentTime=0;video.play()}else video.pause()}
function toggleMotionMute(){const video=$("#viewerVideo");video.muted=!video.muted;syncMotionVolume()}
function motionCoverTime(p){return Math.min(lastMotionFrameTime(p),Math.max(0,p.motion.cover_source==="motion"?p.motion.cover_time_ms:p.motion.still_time_ms||0))}
function freezeMotionAtCover(p){const video=$("#viewerVideo"),apply=()=>{if(state.items[state.viewerIndex]?.id!==p.id||!state.viewerMotion.active)return;video.pause();video.currentTime=motionCoverTime(p)/1000;syncMotionTime()};if(video.readyState>=1)apply();else video.addEventListener("loadedmetadata",apply,{once:true})}
async function locateMotionStillTime(p){if((p?.motion?.still_time_ms??-1)>=0)return;try{const result=await json("/api/motion/locate",{project_id:state.project.id,photo_id:p.id});p.motion.still_time_ms=result.still_time_ms;if(state.items[state.viewerIndex]?.id===p.id){$("#motionTimeline").value=String(motionCoverTime(p));syncMotionCoverMarkers(p);freezeMotionAtCover(p)}}catch{p.motion.still_time_ms=0}}
function setupMotionViewer(p){const video=$("#viewerVideo"),lastFrame=lastMotionFrameTime(p),coverTime=motionCoverTime(p);state.viewerMotion={active:true,scrubbing:false};$("#viewer").classList.add("viewer-motion-open");$("#motionControls").classList.remove("hidden");$("#motionTimeline").max=String(lastFrame);$("#motionTimeline").value=String(coverTime);syncMotionCoverMarkers(p);video.poster=p.photo_url;video.src=p.motion.video_url;video.classList.remove("hidden");$("#viewerImage").classList.add("hidden");resetViewerTransform();syncMotionTime();syncMotionVolume();freezeMotionAtCover(p);locateMotionStillTime(p)}
function chooseMotionSourceWriteback(){const mode=state.settings.motion_cover_writeback||"ask";if(mode==="never")return Promise.resolve(false);if(mode==="always")return Promise.resolve(true);return new Promise(resolve=>{const dialog=$("#motionWritebackConfirm"),checkbox=$("#motionWritebackDontAsk"),yes=$("#motionWritebackYes"),no=$("#motionWritebackNo");let settled=false;checkbox.checked=false;yes.disabled=false;no.disabled=false;const finish=async writeSource=>{if(settled)return;settled=true;yes.disabled=true;no.disabled=true;if(checkbox.checked){const next=writeSource?"always":"never";try{const saved=await json("/api/settings",{motion_cover_writeback:next});state.settings.motion_cover_writeback=saved.settings.motion_cover_writeback||next;$("#motionCoverWriteback").value=state.settings.motion_cover_writeback}catch(error){toast(`保存原图修改设置失败：${error.message}`)}}dialog.close();resolve(writeSource)};yes.onclick=()=>finish(true);no.onclick=()=>finish(false);dialog.oncancel=event=>{event.preventDefault();finish(false)};dialog.showModal()})}
async function saveMotionCover(source="motion",timeMs=null){const p=state.items[state.viewerIndex];if(!p?.motion)return;const button=source==="still"?$("#motionResetCover"):$("#motionSetCover");button.disabled=true;try{const writeSource=source==="motion"?await chooseMotionSourceWriteback():false,requested=timeMs??Math.round($("#viewerVideo").currentTime*1000),selectedTime=source==="motion"?Math.min(lastMotionFrameTime(p),Math.max(0,requested)):0,result=await json("/api/motion/cover",{project_id:state.project.id,photo_id:p.id,source,time_ms:selectedTime,write_source:writeSource});state.items[state.viewerIndex]=result.photo;state.viewerNeedsRefresh=true;state.viewerDirtyIds.add(p.id);applyProjectCounts(result.project_counts);syncCardAnalysis(result.photo);openViewer(state.viewerIndex);toast(source==="still"?"已恢复原始封面":result.source_written?"封面分析已更新，原图已备份并修改":"封面和照片分析已更新")}catch(error){toast(`保存封面失败：${error.message}`)}finally{button.disabled=false}}
function openViewer(i){if(!state.items.length)return;stopViewerMotion();state.viewerIndex=(i+state.items.length)%state.items.length;const p=state.items[state.viewerIndex],suggestion=viewerSuggestion(p),badge=$("#viewerBadge"),analysisBadge=$("#viewerAnalysisBadge"),img=$("#viewerImage");resetViewerTransform();img.classList.remove("hidden");img.src=p.photo_url;$("#viewerName").textContent=p.relative_path.split("/").pop();$("#viewerMeta").textContent=`${p.width||0} × ${p.height||0} · ${formatSize(p.size||0)}${Number.isFinite(p.quality_score)?` · ${p.quality_score} 分`:""}${p.reason?" · "+p.reason:""}${p._blinkLabel?" · 眨眼":""}${p.motion?.error?" · 动态部分不可用":""}`;if(p.media_type==="motion_photo"){badge.innerHTML=LIVE_PHOTO_ICON;badge.setAttribute("aria-label","动态照片");analysisBadge.textContent=suggestion.text;analysisBadge.className=`viewer-badge ${suggestion.kind?`badge-${suggestion.kind}`:"hidden"}`}else{badge.textContent=suggestion.text;badge.removeAttribute("aria-label");analysisBadge.className="viewer-badge hidden"}badge.className=`viewer-badge ${p.media_type==="motion_photo"?"viewer-live-mark":suggestion.kind?`badge-${suggestion.kind}`:"hidden"}`;updateViewerDecision(p);$("#viewerIndex").textContent=`${state.viewerIndex+1} / ${state.items.length}`;if(!$("#viewer").open)$("#viewer").showModal();if(p.motion&&!p.motion.error)setupMotionViewer(p)}
const moveViewer=d=>openViewer(state.viewerIndex+d);

function bindViewerEvents(){
  $("#viewerPrev").onclick=()=>moveViewer(-1);
  $("#viewerNext").onclick=()=>moveViewer(1);
  $("#viewerKeep").onclick=()=>setDecision(state.items[state.viewerIndex].id,"keep");
  $("#viewerRemove").onclick=()=>setDecision(state.items[state.viewerIndex].id,"remove");
  $("#viewer").addEventListener("close",()=>{stopViewerMotion();syncViewerDecisions().catch(error=>toast(error.message))});
  ["timeupdate","play","pause","ended"].forEach(name=>$("#viewerVideo").addEventListener(name,syncMotionTime));
  $("#viewerVideo").addEventListener("volumechange",syncMotionVolume);
  $("#motionMute").onclick=toggleMotionMute;$("#motionPlay").onclick=toggleMotionPlayback;
  $("#motionTimeline").oninput=event=>{$("#viewerVideo").pause();$("#viewerVideo").currentTime=Number(event.target.value)/1000;syncMotionTime()};
  $("#motionSetCover").onclick=()=>saveMotionCover("motion");$("#motionResetCover").onclick=()=>saveMotionCover("still",0);
  $("#viewerImage").addEventListener("click",event=>{if(state.viewerTransform.suppressClick)return;clearTimeout(state.viewerClickTimer);state.viewerClickTimer=setTimeout(()=>zoomViewer(1.5,event.clientX,event.clientY),220)});
  $("#viewerImage").addEventListener("dblclick",event=>{event.preventDefault();clearTimeout(state.viewerClickTimer);resetViewerTransform()});
  $("#viewerVideo").addEventListener("click",()=>{if(!state.viewerTransform.suppressClick)toggleMotionPlayback()});
  [$("#viewerImage"),$("#viewerVideo")].forEach(media=>{media.addEventListener("wheel",event=>{event.preventDefault();zoomViewer(event.deltaY<0?1.18:1/1.18,event.clientX,event.clientY)},{passive:false});media.addEventListener("mousedown",event=>{if(event.button!==0||state.viewerTransform.scale<=1)return;event.preventDefault();const transform=state.viewerTransform;Object.assign(transform,{dragging:true,moved:false,startClientX:event.clientX,startClientY:event.clientY,startX:transform.x,startY:transform.y});applyViewerTransform()})});
  window.addEventListener("mousemove",event=>{const transform=state.viewerTransform;if(!transform.dragging)return;const dx=event.clientX-transform.startClientX,dy=event.clientY-transform.startClientY;if(Math.abs(dx)+Math.abs(dy)>3)transform.moved=true;transform.x=transform.startX+dx;transform.y=transform.startY+dy;clampViewerPan();applyViewerTransform()});
  window.addEventListener("mouseup",()=>{const transform=state.viewerTransform;if(!transform.dragging)return;transform.dragging=false;if(transform.moved){transform.suppressClick=true;setTimeout(()=>transform.suppressClick=false,0)}applyViewerTransform()});
}
